### ISSUE TITLE
Cannot pass in list

### ISSUE THREAD

**Issue by hughsimpson** [sbdchd/squawk-action#9]
Whilst the latest update has apparently fixed globbing, it still seems to be impossible to pass in a list of literals to the action

**Comment by Agraphie** [comment]
We have the same issue. I think the issue is that `compgen -G` will expand the first path, but omit the second. I haven't found a good way to support both, globs & multiple file paths. So I introduced another input variable where you can specify multiple (space separated) files

https://github.com/sbdchd/squawk-action/pull/10
